@startuml RF04

class modificar_carrito{
    - producto: String
    - nueva_cantidad : String
   
}

class eliminar_producto extends modificar_carrito {
    - producto : String
    
}
@enduml